# Generated by Django 5.1.4 on 2025-01-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_image_url_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
