# Generated by Django 5.1.4 on 2025-01-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cart_total_price_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
