# Generated by Django 5.1.4 on 2025-01-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
