# Generated by Django 5.1.4 on 2025-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=12, unique=True),
        ),
    ]
